## aowlui/lab/components — GENERATED by tools/ingest from
## reference/styles.css. Do not edit by hand; edit the ingester or the
## reference sheet and regenerate. tests/tround.nim proves this renders
## back to the original declarations.

import ../component
export component

proc labComponents*(): seq[Component] =
  result = @[
    Component(name: "bubble", family: "bubble", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "user-select: text", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "width: fit-content; max-width: min(74%, 42rem); padding: 0.78rem 1rem; border-radius: 1.25rem; line-height: 1.45; white-space: pre-wrap; overflow-wrap: anywhere; box-shadow: var(--bubble-shadow)", note: ""),
    ]),
    Component(name: "markdown-body", family: "markdown", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "user-select: text", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "white-space: normal", note: ""),
      Rule(part: " > :first-child", kind: stBase, flag: "", sel: "", decls: "margin-top: 0", note: ""),
      Rule(part: " > :last-child", kind: stBase, flag: "", sel: "", decls: "margin-bottom: 0", note: ""),
      Rule(part: " p", kind: stBase, flag: "", sel: "", decls: "margin: 0.3rem 0", note: ""),
      Rule(part: " h2", kind: stBase, flag: "", sel: "", decls: "margin: 0.55rem 0 0.3rem; font-size: 1rem; line-height: 1.25; letter-spacing: 0", note: ""),
      Rule(part: " h3", kind: stBase, flag: "", sel: "", decls: "margin: 0.55rem 0 0.3rem; font-size: 1rem; line-height: 1.25; letter-spacing: 0", note: ""),
      Rule(part: " h4", kind: stBase, flag: "", sel: "", decls: "margin: 0.55rem 0 0.3rem; font-size: 1rem; line-height: 1.25; letter-spacing: 0", note: ""),
      Rule(part: " ul", kind: stBase, flag: "", sel: "", decls: "margin: 0.38rem 0; padding-left: 1.2rem", note: ""),
      Rule(part: " ol", kind: stBase, flag: "", sel: "", decls: "margin: 0.38rem 0; padding-left: 1.2rem", note: ""),
      Rule(part: " li", kind: stBase, flag: "", sel: "", decls: "margin: 0.22rem 0", note: ""),
      Rule(part: " code", kind: stBase, flag: "", sel: "", decls: "padding: 0.12rem 0.32rem; border: 1px solid var(--trace-item-border); border-radius: 0.38rem; background: var(--trace); color: var(--trace-code); font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.88em", note: ""),
      Rule(part: " pre", kind: stBase, flag: "", sel: "", decls: "max-width: 100%; margin: 0.55rem 0; padding: 0.72rem; border: 1px solid var(--trace-item-border); border-radius: 0.8rem; background: var(--trace); overflow-x: auto", note: ""),
      Rule(part: " pre code", kind: stBase, flag: "", sel: "", decls: "display: block; padding: 0; border: 0; border-radius: 0; background: transparent; white-space: pre", note: ""),
      Rule(part: " blockquote", kind: stBase, flag: "", sel: "", decls: "margin: 0.5rem 0; padding-left: 0.75rem; border-left: 3px solid var(--hairline); color: var(--muted)", note: ""),
      Rule(part: " a", kind: stBase, flag: "", sel: "", decls: "color: var(--link); text-decoration-thickness: 0.08em; text-underline-offset: 0.18em", note: ""),
    ]),
    Component(name: "trace-item", family: "trace", doc: "", element: "", rules: @[
      Rule(part: " pre", kind: stBase, flag: "", sel: "", decls: "user-select: text", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "border: 1px solid var(--trace-item-border); border-radius: 0.74rem; background: var(--trace); overflow: hidden", note: ""),
      Rule(part: " pre", kind: stBase, flag: "", sel: "", decls: "margin: 0; padding: 0.68rem; border-top: 1px solid var(--trace-item-border); color: var(--trace-code); font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.78rem; line-height: 1.5; white-space: pre-wrap; overflow-wrap: anywhere", note: ""),
    ]),
    Component(name: "activity-body", family: "activity", doc: "", element: "", rules: @[
      Rule(part: " pre", kind: stBase, flag: "", sel: "", decls: "user-select: text", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; gap: 0.35rem; padding: 0 0.62rem 0.62rem", note: ""),
      Rule(part: " pre", kind: stBase, flag: "", sel: "", decls: "margin: 0; max-height: 10rem; padding: 0.58rem; border: 1px solid var(--trace-item-border); border-radius: 0.72rem; background: var(--trace); color: var(--trace-code); font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.76rem; line-height: 1.45; white-space: pre-wrap; overflow: auto; overflow-wrap: anywhere", note: ""),
    ]),
    Component(name: "memory-item", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "user-select: text", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; justify-content: space-between; gap: 0.75rem; padding: 0.78rem; border: 1px solid var(--hairline); border-radius: 1rem; background: color-mix(in srgb, var(--assistant) 88%, transparent)", note: ""),
      Rule(part: " h4", kind: stBase, flag: "", sel: "", decls: "margin: 0; font-size: 0.95rem; line-height: 1.25; letter-spacing: 0; overflow-wrap: anywhere", note: ""),
      Rule(part: " h4 span", kind: stBase, flag: "", sel: "", decls: "color: var(--accent)", note: ""),
      Rule(part: " p", kind: stBase, flag: "", sel: "", decls: "margin: 0.28rem 0 0; color: var(--muted); font-size: 0.8rem; line-height: 1.35; overflow-wrap: anywhere", note: ""),
      Rule(part: " button", kind: stBase, flag: "", sel: "", decls: "flex: 0 0 auto; min-height: 2rem; border: 1px solid var(--hairline); border-radius: 999px; background: var(--control-bg); color: var(--text); cursor: pointer", note: ""),
      Rule(part: "", kind: stFlag, flag: "focusable", sel: "", decls: "cursor: pointer; transition: border-color 0.12s ease, background 0.12s ease", note: ""),
    ]),
    Component(name: "code-main", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "user-select: text", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-width: 0; background: var(--assistant); display: flex; flex-direction: column", note: ""),
    ]),
    Component(name: "code-block", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "user-select: text", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "margin: 0; padding: 1rem; overflow: auto; color: var(--trace-code); font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.84rem; line-height: 1.55; white-space: pre", note: ""),
    ]),
    Component(name: "code-meta", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "user-select: text", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "color: var(--muted); font-size: 0.74rem; font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding: 0.62rem 0.7rem; border-top: 1px solid var(--hairline)", note: ""),
    ]),
    Component(name: "monaco-host", family: "monaco", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "user-select: text", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "width: 100%; height: 3.5rem", note: ""),
      Rule(part: "", kind: stFlag, flag: "monaco-fallback", sel: "", decls: "height: auto", note: ""),
    ]),
    Component(name: "app-shell", family: "app", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; grid-template-rows: auto 1fr auto; height: 100vh; height: 100dvh", note: ""),
    ]),
    Component(name: "topbar", family: "topbar", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "z-index: 10; display: flex; align-items: center; justify-content: space-between; gap: 1rem; padding: calc(env(safe-area-inset-top) + 0.8rem) clamp(1rem, 4vw, 2rem) 0.8rem; border-bottom: 1px solid var(--hairline); background: var(--topbar-bg); backdrop-filter: blur(22px) saturate(1.25)", note: ""),
    ]),
    Component(name: "brand", family: "brand", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; min-width: 0; gap: 0.72rem", note: ""),
    ]),
    Component(name: "brand-logo", family: "brand", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: block; width: clamp(5.3rem, 10vw, 7.4rem); height: auto; max-height: 1.9rem; object-fit: contain; filter: invert(1); user-select: none", note: ""),
    ]),
    Component(name: "brand-subtitle", family: "brand", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "margin-top: 0.18rem; color: var(--muted); font-size: 0.78rem; line-height: 1.2", note: ""),
    ]),
    Component(name: "top-actions", family: "top", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; justify-content: flex-end; gap: 0.45rem; min-width: 0", note: ""),
    ]),
    Component(name: "ghost-button", family: "ghost", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "border: 0; cursor: pointer", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-height: 2.35rem; padding: 0 0.95rem; border: 1px solid var(--hairline); border-radius: 999px; background: var(--control-bg); color: var(--control-color); transition: transform 160ms var(--ease), background 160ms var(--ease)", note: ""),
      Rule(part: "", kind: stHover, flag: "", sel: "", decls: "background: var(--control-hover); transform: translateY(-1px)", note: ""),
      Rule(part: "", kind: stFlag, flag: "active", sel: "", decls: "border-color: color-mix(in srgb, var(--accent) 48%, transparent); background: color-mix(in srgb, var(--accent) 18%, transparent); color: var(--text)", note: ""),
    ]),
    Component(name: "mode-tab", family: "mode", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "border: 0; cursor: pointer", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-width: 3.2rem; min-height: 2.08rem; padding: 0 0.7rem; border-radius: 999px; background: transparent; color: var(--tab-color); font-size: 0.86rem; font-weight: 700", note: ""),
      Rule(part: "", kind: stFlag, flag: "active", sel: "", decls: "background: var(--tab-active-bg); color: var(--text); box-shadow: var(--bubble-shadow)", note: ""),
    ]),
    Component(name: "send-button", family: "send", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "border: 0; cursor: pointer", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-width: 4.2rem; min-height: 2.35rem; padding: 0 1rem; border-radius: 999px; background: var(--send-bg); color: var(--send-color); font-weight: 720; transition: transform 160ms var(--ease), opacity 160ms var(--ease)", note: ""),
      Rule(part: "", kind: stHover, flag: "", sel: "", decls: "transform: translateY(-1px)", note: ""),
      Rule(part: "", kind: stDisabled, flag: "", sel: "", decls: "cursor: default; opacity: 0.48; transform: none", note: ""),
    ]),
    Component(name: "prompt-chip", family: "prompt", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "border: 0; cursor: pointer", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-height: 2.35rem; padding: 0 0.9rem; border: 1px solid var(--hairline); border-radius: 999px; background: var(--chip-bg); color: var(--chip-color); font-size: 0.9rem; transition: transform 160ms var(--ease), border-color 160ms var(--ease)", note: ""),
      Rule(part: "", kind: stHover, flag: "", sel: "", decls: "border-color: color-mix(in srgb, var(--user) 42%, transparent); transform: translateY(-1px)", note: ""),
    ]),
    Component(name: "trace-toggle", family: "trace", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "border: 0; cursor: pointer", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; justify-content: space-between; width: 100%; min-height: 2.45rem; padding: 0 0.82rem; background: var(--trace-toggle-bg); color: var(--trace-ink); text-align: left", note: ""),
    ]),
    Component(name: "icon-button", family: "icon", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: inline-flex; align-items: center; justify-content: center; gap: 0.42rem; padding: 0 0.72rem", note: ""),
      Rule(part: " svg", kind: stBase, flag: "", sel: "", decls: "width: 1.02rem; height: 1.02rem; fill: none; stroke: currentColor; stroke-width: 1.9; stroke-linecap: round; stroke-linejoin: round; flex: 0 0 auto", note: ""),
      Rule(part: " span", kind: stBase, flag: "", sel: "", decls: "font-size: 0.82rem; font-weight: 700", note: ""),
    ]),
    Component(name: "conversation", family: "conversation", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-height: 0; overflow-y: auto; padding: clamp(1rem, 3vw, 2rem) clamp(0.82rem, 4vw, 2rem) 1.2rem; scroll-behavior: smooth", note: ""),
    ]),
    Component(name: "conversation-inner", family: "conversation", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "max-width: 920px; margin: 0 auto", note: ""),
    ]),
    Component(name: "welcome-card", family: "welcome", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "max-width: 760px; margin: clamp(2rem, 10vh, 6rem) auto 0; padding: clamp(1.2rem, 4vw, 2rem); border: 1px solid var(--hairline); border-radius: var(--radius); background: var(--panel); box-shadow: var(--shadow); animation: riseIn 420ms var(--ease) both", note: ""),
      Rule(part: " h1", kind: stBase, flag: "", sel: "", decls: "margin: 0; font-size: clamp(2rem, 7vw, 4.8rem); line-height: 0.98; letter-spacing: 0", note: ""),
      Rule(part: " p:not(.eyebrow)", kind: stBase, flag: "", sel: "", decls: "max-width: 38rem; margin: 1rem 0 0; color: var(--copy); font-size: clamp(1rem, 2vw, 1.12rem); line-height: 1.55", note: ""),
    ]),
    Component(name: "eyebrow", family: "eyebrow", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "margin: 0 0 0.7rem; color: var(--accent); font-size: 0.76rem; font-weight: 760; letter-spacing: 0; text-transform: uppercase", note: ""),
    ]),
    Component(name: "prompt-row", family: "prompt", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; flex-wrap: wrap; gap: 0.55rem; margin-top: 1.35rem", note: ""),
    ]),
    Component(name: "owl-home", family: "owl", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "max-width: none; min-height: min(64vh, 560px); margin: 0 auto; padding: 0; border: none; background: none; box-shadow: none; display: flex; align-items: center; justify-content: center", note: ""),
    ]),
    Component(name: "owl-mover", family: "owl", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative; display: flex; justify-content: center; will-change: transform", note: ""),
    ]),
    Component(name: "owl-mark", family: "owl", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "width: clamp(228px, 42vw, 380px); height: auto; color: var(--muted); opacity: 0.16; transition: opacity 600ms var(--ease)", note: ""),
      Rule(part: " .owl-ring", kind: stBase, flag: "", sel: "", decls: "fill: none; stroke: currentColor; stroke-width: 5", note: ""),
      Rule(part: " .owl-brow", kind: stBase, flag: "", sel: "", decls: "fill: currentColor", note: ""),
      Rule(part: " .owl-pupil", kind: stBase, flag: "", sel: "", decls: "fill: currentColor", note: ""),
      Rule(part: " .owl-beak", kind: stBase, flag: "", sel: "", decls: "fill: currentColor", note: ""),
      Rule(part: "", kind: stFlag, flag: "awake", sel: "", decls: "opacity: 0.32; --pdilate: 1.3", note: ""),
    ]),
    Component(name: "owl-eye", family: "owl", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "transform-box: fill-box; transform-origin: center; transition: transform 300ms var(--ease)", note: ""),
    ]),
    Component(name: "owl-pupil", family: "owl", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "transform-box: fill-box; transform-origin: center; transform: translate(calc(var(--px, 0) * 1px), calc(var(--py, 0) * 1px))\n    scale(var(--pdilate, 1)); transition: transform 220ms var(--ease)", note: ""),
    ]),
    Component(name: "thread", family: "thread", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "width: min(920px, 100%); margin: 0 auto", note: ""),
    ]),
    Component(name: "message", family: "message", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; flex-direction: column; margin: 0.72rem 0; animation: bubbleIn 240ms var(--ease) both", note: ""),
      Rule(part: "", kind: stFlag, flag: "user", sel: "", decls: "align-items: flex-end", note: ""),
      Rule(part: "", kind: stFlag, flag: "assistant", sel: "", decls: "align-items: flex-start", note: ""),
      Rule(part: "", kind: stFlag, flag: "system", sel: "", decls: "align-items: flex-start", note: ""),
    ]),
    Component(name: "user", family: "user", doc: "", element: "", rules: @[
      Rule(part: " .bubble", kind: stBase, flag: "", sel: "", decls: "border-bottom-right-radius: 0.38rem; background: var(--user); color: #fff", note: ""),
      Rule(part: " .markdown-body code", kind: stBase, flag: "", sel: "", decls: "border-color: rgba(255, 255, 255, 0.2); background: rgba(0, 0, 0, 0.22); color: #fff", note: ""),
      Rule(part: " .markdown-body pre", kind: stBase, flag: "", sel: "", decls: "border-color: rgba(255, 255, 255, 0.2); background: rgba(0, 0, 0, 0.22); color: #fff", note: ""),
      Rule(part: " .markdown-body a", kind: stBase, flag: "", sel: "", decls: "color: #fff", note: ""),
    ]),
    Component(name: "assistant", family: "assistant", doc: "", element: "", rules: @[
      Rule(part: " .bubble", kind: stBase, flag: "", sel: "", decls: "border: 1px solid var(--assistant-border); border-bottom-left-radius: 0.38rem; background: var(--assistant); color: var(--text)", note: ""),
    ]),
    Component(name: "system", family: "system", doc: "", element: "", rules: @[
      Rule(part: " .bubble", kind: stBase, flag: "", sel: "", decls: "border: 1px solid var(--system-border); background: var(--system-bg); color: var(--warning)", note: ""),
    ]),
    Component(name: "typing", family: "typing", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: inline-flex; align-items: center; gap: 0.28rem", note: ""),
      Rule(part: " span", kind: stBase, flag: "", sel: "", decls: "width: 0.38rem; height: 0.38rem; border-radius: 50%; background: var(--typing-dot); animation: pulse 900ms infinite ease-in-out", note: ""),
      Rule(part: " span:nth-child(2)", kind: stBase, flag: "", sel: "", decls: "animation-delay: 120ms", note: ""),
      Rule(part: " span:nth-child(3)", kind: stBase, flag: "", sel: "", decls: "animation-delay: 240ms", note: ""),
    ]),
    Component(name: "trace", family: "trace", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: none; width: min(74%, 42rem); margin-top: 0.38rem; border: 1px solid var(--trace-border); border-radius: 1rem; background: var(--trace-panel); overflow: hidden", note: ""),
    ]),
    Component(name: "developer-mode", family: "developer", doc: "", element: "", rules: @[
      Rule(part: " .trace", kind: stBase, flag: "", sel: "", decls: "display: block", note: ""),
    ]),
    Component(name: "trace-title", family: "trace", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: 0.84rem; font-weight: 720", note: ""),
    ]),
    Component(name: "trace-count", family: "trace", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "color: var(--muted); font-size: 0.78rem", note: ""),
    ]),
    Component(name: "trace-body", family: "trace", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; gap: 0.45rem; padding: 0.65rem", note: ""),
    ]),
    Component(name: "trace-item-head", family: "trace", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: baseline; justify-content: space-between; gap: 0.6rem; padding: 0.58rem 0.68rem; color: var(--trace-ink); font-size: 0.82rem; font-weight: 720", note: ""),
    ]),
    Component(name: "activity-stack", family: "activity", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; gap: 0.42rem; width: min(74%, 42rem); margin-top: 0.42rem", note: ""),
    ]),
    Component(name: "activity-card", family: "activity", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "border: 1px solid var(--hairline); border-radius: 1rem; background: linear-gradient(135deg, color-mix(in srgb, var(--accent) 10%, transparent), transparent 58%),\n    color-mix(in srgb, var(--assistant) 88%, transparent); overflow: hidden; box-shadow: var(--bubble-shadow)", note: ""),
      Rule(part: " summary", kind: stBase, flag: "", sel: "", decls: "list-style: none", note: ""),
      Rule(part: " summary::-webkit-details-marker", kind: stBase, flag: "", sel: "", decls: "display: none", note: ""),
    ]),
    Component(name: "activity-summary", family: "activity", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; grid-template-columns: auto minmax(0, 1fr) auto; align-items: center; gap: 0.65rem; min-height: 2.65rem; padding: 0.48rem 0.62rem; cursor: pointer", note: ""),
    ]),
    Component(name: "activity-mark", family: "activity", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; place-items: center; width: 1.72rem; height: 1.72rem; border: 1px solid var(--hairline); border-radius: 0.55rem; background: color-mix(in srgb, var(--accent) 18%, transparent); color: var(--accent); font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.72rem; font-weight: 760", note: ""),
    ]),
    Component(name: "attachment-mark", family: "attachment", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; place-items: center; width: 1.72rem; height: 1.72rem; border: 1px solid var(--hairline); border-radius: 0.55rem; background: color-mix(in srgb, var(--accent) 18%, transparent); color: var(--accent); font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.72rem; font-weight: 760", note: ""),
    ]),
    Component(name: "activity-title", family: "activity", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-width: 0; color: var(--text); font-size: 0.86rem; font-weight: 720; overflow: hidden; text-overflow: ellipsis; white-space: nowrap", note: ""),
    ]),
    Component(name: "activity-status", family: "activity", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "color: var(--muted); font-size: 0.74rem; text-transform: uppercase", note: ""),
    ]),
    Component(name: "activity-label", family: "activity", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "color: var(--muted); font-size: 0.68rem; font-weight: 760; text-transform: uppercase", note: ""),
    ]),
    Component(name: "composer-wrap", family: "composer", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding: 0.7rem clamp(0.75rem, 4vw, 2rem) calc(env(safe-area-inset-bottom) + 0.85rem); border-top: 1px solid var(--hairline); background: var(--topbar-bg); backdrop-filter: blur(22px) saturate(1.2)", note: ""),
    ]),
    Component(name: "composer", family: "composer", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; grid-template-columns: auto 1fr auto; align-items: end; gap: 0.58rem; width: min(920px, 100%); margin: 0 auto; padding: 0.5rem; border: 1px solid var(--hairline); border-radius: 1.35rem; background: var(--composer-bg); box-shadow: var(--shadow)", note: ""),
    ]),
    Component(name: "mode-tabs", family: "mode", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; gap: 0.2rem; padding: 0.18rem; border: 1px solid var(--hairline); border-radius: 999px; background: var(--tab-bg)", note: ""),
    ]),
    Component(name: "sr-only", family: "sr", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border: 0", note: ""),
    ]),
    Component(name: "memory-panel", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: fixed; inset: 0; z-index: 40; display: none", note: ""),
      Rule(part: "", kind: stFlag, flag: "open", sel: "", decls: "display: block", note: ""),
    ]),
    Component(name: "memory-scrim", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: absolute; inset: 0; background: var(--page-end)", note: ""),
    ]),
    Component(name: "memory-sheet", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: absolute; inset: 0; display: grid; grid-template-rows: auto auto 1fr; overflow: hidden; border: 0; border-radius: 0; background: radial-gradient(circle at 18% 0%, color-mix(in srgb, var(--accent) 12%, transparent), transparent 28rem),\n    var(--panel); animation: sheetIn 180ms var(--ease) both", note: ""),
    ]),
    Component(name: "memory-sheet-head", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; justify-content: space-between; gap: 1rem; padding: 0.45rem clamp(0.85rem, 3vw, 1.2rem); border-bottom: 1px solid var(--hairline)", note: ""),
      Rule(part: " .eyebrow", kind: stBase, flag: "", sel: "", decls: "display: none", note: ""),
      Rule(part: " h2", kind: stBase, flag: "", sel: "", decls: "margin: 0; font-size: 1.22rem; line-height: 1.2; letter-spacing: 0; font-weight: 650", note: ""),
    ]),
    Component(name: "memory-toolbar", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; flex-wrap: wrap; gap: 0.5rem; padding: 0.4rem clamp(0.7rem, 2vw, 0.9rem); border-bottom: 1px solid var(--hairline); background: color-mix(in srgb, var(--trace) 55%, transparent)", note: ""),
      Rule(part: " input", kind: stBase, flag: "", sel: "", decls: "flex: 1; min-width: 0; min-height: 2.1rem; border: 0; border-radius: 0; outline: 0; padding: 0 0.8rem 0 1.9rem; background: transparent; color: var(--text); font-size: 0.92rem", note: ""),
      Rule(part: " input::placeholder", kind: stBase, flag: "", sel: "", decls: "color: var(--placeholder)", note: ""),
    ]),
    Component(name: "memory-filters", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; flex-wrap: wrap; gap: 0.3rem", note: ""),
    ]),
    Component(name: "memory-actions", family: "memory", doc: "", element: "", rules: @[
      Rule(part: " .icon-button", kind: stBase, flag: "", sel: "", decls: "width: 2.2rem; height: 2.2rem; padding: 0; border: 1px solid var(--hairline); border-radius: 0.6rem; background: var(--control-bg); color: var(--text); cursor: pointer", note: ""),
      Rule(part: " .icon-button:hover", kind: stBase, flag: "", sel: "", decls: "background: var(--control-hover); border-color: color-mix(in srgb, var(--accent) 40%, var(--hairline))", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; justify-content: flex-end; gap: 0.45rem", note: ""),
    ]),
    Component(name: "memory-tabs", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "grid-column: 1 / -1; display: flex; align-items: center; gap: 0.35rem; overflow-x: auto; padding-bottom: 0.1rem", note: ""),
      Rule(part: "", kind: stEmpty, flag: "", sel: "", decls: "display: none", note: ""),
    ]),
    Component(name: "memory-tab", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-height: 2.35rem; padding: 0 0.82rem; border: 1px solid var(--hairline); border-radius: 999px; background: var(--control-bg); color: var(--tab-color); cursor: pointer", note: ""),
      Rule(part: "", kind: stFlag, flag: "active", sel: "", decls: "background: var(--tab-active-bg); color: var(--text)", note: ""),
    ]),
    Component(name: "memory-content", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-height: 0; overflow: hidden; padding: 0", note: ""),
      Rule(part: "", kind: stFlag, flag: "compact", sel: "", decls: "padding: 0; overflow: visible", note: ""),
    ]),
    Component(name: "memory-oracle-wrap", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative; min-height: 12.5rem; margin-bottom: 0.82rem; border: 1px solid var(--hairline); border-radius: 1.25rem; background: linear-gradient(180deg, color-mix(in srgb, var(--panel-solid) 78%, transparent), transparent),\n    radial-gradient(circle at 50% 35%, color-mix(in srgb, var(--user) 16%, transparent), transparent 28rem),\n    color-mix(in srgb, var(--assistant) 82%, transparent); overflow: hidden; box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.04); touch-action: none", note: ""),
      Rule(part: "", kind: stBefore, flag: "", sel: "", decls: "content: \"\"; position: absolute; inset: 0; pointer-events: none", note: ""),
      Rule(part: "", kind: stAfter, flag: "", sel: "", decls: "content: \"\"; position: absolute; inset: 0; pointer-events: none", note: ""),
      Rule(part: "", kind: stBefore, flag: "", sel: "", decls: "background: linear-gradient(115deg, rgba(255, 255, 255, 0.12), transparent 24%, transparent 72%, rgba(255, 255, 255, 0.05)),\n    repeating-linear-gradient(90deg, rgba(255, 255, 255, 0.025) 0, rgba(255, 255, 255, 0.025) 1px, transparent 1px, transparent 12px); mix-blend-mode: screen", note: ""),
      Rule(part: "", kind: stAfter, flag: "", sel: "", decls: "border-radius: inherit; box-shadow: inset 0 0 70px rgba(0, 0, 0, 0.34)", note: ""),
      Rule(part: "", kind: stFlag, flag: "compact-oracle", sel: "", decls: "min-height: 8.25rem", note: ""),
    ]),
    Component(name: "memory-oracle", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: block; width: 100%; height: 100%; min-height: inherit; cursor: grab", note: ""),
      Rule(part: "", kind: stActive, flag: "", sel: "", decls: "cursor: grabbing", note: ""),
    ]),
    Component(name: "memory-oracle-empty", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: absolute; inset: 0; z-index: 1; display: grid; place-items: center; padding: 1rem; color: var(--muted); font-size: 0.84rem; text-align: center; background: linear-gradient(180deg, rgba(0, 0, 0, 0.04), transparent 30%, rgba(0, 0, 0, 0.08)); pointer-events: none", note: ""),
    ]),
    Component(name: "oracle-controls", family: "oracle", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; flex-wrap: wrap; gap: 0.35rem; margin-bottom: 0.7rem", note: ""),
    ]),
    Component(name: "oracle-filter", family: "oracle", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-height: 2rem; padding: 0 0.64rem; border: 1px solid var(--hairline); border-radius: 999px; background: color-mix(in srgb, var(--panel-solid) 68%, transparent); color: var(--muted); font-size: 0.76rem; font-weight: 720; cursor: pointer; backdrop-filter: blur(14px) saturate(1.2)", note: ""),
      Rule(part: "", kind: stFlag, flag: "active", sel: "", decls: "border-color: color-mix(in srgb, var(--accent) 46%, transparent); background: color-mix(in srgb, var(--accent) 18%, transparent); color: var(--text)", note: ""),
    ]),
    Component(name: "oracle-source", family: "oracle", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "margin-left: auto; padding: 0.36rem 0.55rem; border: 1px solid var(--hairline); border-radius: 999px; background: color-mix(in srgb, var(--panel-solid) 58%, transparent); color: var(--muted); font-size: 0.7rem; text-transform: uppercase; backdrop-filter: blur(14px) saturate(1.2)", note: ""),
    ]),
    Component(name: "memory-oracle-glass", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: absolute; left: 0.78rem; right: 0.78rem; bottom: 0.72rem; display: flex; justify-content: center; pointer-events: none", note: ""),
      Rule(part: " span", kind: stBase, flag: "", sel: "", decls: "max-width: 100%; padding: 0.42rem 0.72rem; border: 1px solid var(--hairline); border-radius: 999px; background: color-mix(in srgb, var(--panel-solid) 70%, transparent); color: var(--muted); font-size: 0.78rem; line-height: 1.2; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; backdrop-filter: blur(16px) saturate(1.25)", note: ""),
    ]),
    Component(name: "memory-grid", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; grid-template-columns: repeat(6, minmax(0, 1fr)); gap: 0.42rem", note: ""),
    ]),
    Component(name: "memory-metric", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-height: 3.35rem; padding: 0.55rem 0.62rem; border: 1px solid var(--hairline); border-radius: 0.82rem; background: color-mix(in srgb, var(--assistant) 86%, transparent)", note: ""),
      Rule(part: " span", kind: stBase, flag: "", sel: "", decls: "display: block; color: var(--muted); font-size: 0.68rem; font-weight: 720", note: ""),
      Rule(part: " strong", kind: stBase, flag: "", sel: "", decls: "display: block; margin-top: 0.28rem; font-size: clamp(1.05rem, 2vw, 1.35rem); line-height: 1", note: ""),
    ]),
    Component(name: "memory-section", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "margin-top: 1rem", note: ""),
      Rule(part: " h3", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: baseline; justify-content: space-between; gap: 0.75rem; margin: 0 0 0.62rem; font-size: 0.94rem; letter-spacing: 0", note: ""),
      Rule(part: " h3 span", kind: stBase, flag: "", sel: "", decls: "color: var(--muted); font-size: 0.78rem", note: ""),
    ]),
    Component(name: "memory-list", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; gap: 0.55rem", note: ""),
    ]),
    Component(name: "memory-empty", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding: 1.1rem; border: 1px solid var(--hairline); border-radius: 1rem; background: var(--control-bg); color: var(--muted)", note: ""),
    ]),
    Component(name: "memory-loading", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding: 1.1rem; border: 1px solid var(--hairline); border-radius: 1rem; background: var(--control-bg); color: var(--muted)", note: ""),
    ]),
    Component(name: "view-attachment", family: "view", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "width: min(74%, 46rem); margin-top: 0.45rem; padding: 0.72rem; border: 1px solid var(--hairline); border-radius: 1.25rem; background: radial-gradient(circle at 30% 0%, color-mix(in srgb, var(--user) 18%, transparent), transparent 18rem),\n    var(--panel); box-shadow: var(--shadow)", note: ""),
    ]),
    Component(name: "attachment-shell", family: "attachment", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "overflow: hidden; border-radius: 0.98rem", note: ""),
      Rule(part: " summary", kind: stBase, flag: "", sel: "", decls: "list-style: none", note: ""),
      Rule(part: " summary::-webkit-details-marker", kind: stBase, flag: "", sel: "", decls: "display: none", note: ""),
    ]),
    Component(name: "attachment-summary", family: "attachment", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; grid-template-columns: auto minmax(0, 1fr); align-items: center; gap: 0.68rem; min-height: 3.1rem; cursor: pointer", note: ""),
    ]),
    Component(name: "attachment-copy", family: "attachment", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; min-width: 0; gap: 0.16rem", note: ""),
      Rule(part: " strong", kind: stBase, flag: "", sel: "", decls: "min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap", note: ""),
      Rule(part: " span", kind: stBase, flag: "", sel: "", decls: "min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap", note: ""),
      Rule(part: " strong", kind: stBase, flag: "", sel: "", decls: "color: var(--text); font-size: 0.94rem", note: ""),
      Rule(part: " span", kind: stBase, flag: "", sel: "", decls: "color: var(--muted); font-size: 0.78rem", note: ""),
    ]),
    Component(name: "attachment-body", family: "attachment", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding-top: 0.7rem", note: ""),
    ]),
    Component(name: "open-memory-button", family: "open", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "margin-top: 0.7rem", note: ""),
    ]),
    Component(name: "memory-card-head", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; justify-content: space-between; gap: 0.75rem; margin-bottom: 0.72rem", note: ""),
      Rule(part: " h3", kind: stBase, flag: "", sel: "", decls: "margin: 0; font-size: 1.05rem; letter-spacing: 0", note: ""),
    ]),
    Component(name: "code-view", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; grid-template-columns: minmax(8.5rem, 12.5rem) minmax(0, 1fr); gap: 0; min-height: 18rem; border: 1px solid var(--hairline); border-radius: 0.9rem; background: var(--control-bg); overflow: hidden", note: ""),
    ]),
    Component(name: "code-sidebar", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-width: 0; padding: 0.6rem 0.55rem; border-right: 1px solid var(--hairline); background: color-mix(in srgb, var(--trace) 60%, transparent)", note: ""),
    ]),
    Component(name: "code-sidebar-title", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "color: var(--muted); font-size: 0.66rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.14em; padding: 0.1rem 0.4rem 0.5rem", note: ""),
    ]),
    Component(name: "code-unit-list", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; gap: 0.22rem", note: ""),
    ]),
    Component(name: "code-unit", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-height: 2.05rem; padding: 0 0.55rem; border: 1px solid transparent; border-radius: 0.5rem; background: transparent; color: var(--text); text-align: left; font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.8rem; cursor: pointer; transition: background 0.14s var(--ease), border-color 0.14s var(--ease)", note: ""),
      Rule(part: "", kind: stHover, flag: "", sel: "", decls: "background: var(--control-hover)", note: ""),
      Rule(part: "", kind: stFlag, flag: "active", sel: "", decls: "border-color: color-mix(in srgb, var(--accent) 45%, var(--hairline)); background: color-mix(in srgb, var(--accent) 12%, transparent); color: var(--text); box-shadow: inset 2px 0 0 var(--accent)", note: ""),
    ]),
    Component(name: "code-panel-head", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; gap: 0.7rem; padding: 0.62rem 0.7rem; border-bottom: 1px solid var(--hairline); background: color-mix(in srgb, var(--trace) 40%, transparent)", note: ""),
      Rule(part: " h3", kind: stBase, flag: "", sel: "", decls: "margin: 0; font-size: 0.98rem; letter-spacing: 0; font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; overflow: hidden; text-overflow: ellipsis; white-space: nowrap", note: ""),
    ]),
    Component(name: "code-panel-id", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-width: 0; flex: 1", note: ""),
      Rule(part: " .eyebrow", kind: stBase, flag: "", sel: "", decls: "text-transform: uppercase; letter-spacing: 0.16em; font-size: 0.62rem; margin: 0 0 0.1rem", note: ""),
    ]),
    Component(name: "code-atom-id", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "color: var(--muted); font-size: 0.74rem; font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace", note: ""),
    ]),
    Component(name: "code-view-toggle", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: inline-flex; padding: 0.14rem; gap: 0.14rem; border: 1px solid var(--hairline); border-radius: 0.55rem; background: var(--control-bg)", note: ""),
    ]),
    Component(name: "code-view-tab", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "border: 0; border-radius: 0.42rem; padding: 0.22rem 0.62rem; background: transparent; color: var(--muted); font-size: 0.7rem; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase; cursor: pointer", note: ""),
      Rule(part: "", kind: stFlag, flag: "active", sel: "", decls: "background: var(--accent); color: var(--mark-color)", note: ""),
    ]),
    Component(name: "code-ref-row", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; flex-wrap: wrap; gap: 0.4rem; padding: 0.5rem 0.7rem; border-bottom: 1px solid var(--hairline)", note: ""),
    ]),
    Component(name: "code-ref", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-height: 1.7rem; padding: 0 0.55rem; border: 1px solid var(--hairline); border-radius: 0.45rem; background: color-mix(in srgb, var(--link) 12%, transparent); color: var(--link); font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.74rem", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "cursor: pointer", note: ""),
    ]),
    Component(name: "code-ref-empty", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-height: 1.7rem; padding: 0 0.55rem; border: 1px solid var(--hairline); border-radius: 0.45rem; background: color-mix(in srgb, var(--link) 12%, transparent); color: var(--link); font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.74rem", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: inline-flex; align-items: center; background: transparent; color: var(--muted)", note: ""),
    ]),
    Component(name: "code-pane", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-width: 0", note: ""),
    ]),
    Component(name: "monaco-shell", family: "monaco", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-height: 0; background: var(--trace)", note: ""),
    ]),
    Component(name: "monaco-code-ref", family: "monaco", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "background: color-mix(in srgb, var(--accent) 20%, transparent); border: 1px solid color-mix(in srgb, var(--accent) 55%, transparent); border-radius: 0.28rem; box-shadow: inset 0 -1px 0 var(--accent); cursor: pointer; transition: background 0.12s ease", note: ""),
      Rule(part: "", kind: stHover, flag: "", sel: "", decls: "background: color-mix(in srgb, var(--accent) 34%, transparent)", note: ""),
    ]),
    Component(name: "ast-children", family: "ast", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "list-style: none; margin: 0; padding: 0", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "margin-left: 0.85rem; padding-left: 0.6rem; border-left: 1px solid var(--hairline)", note: ""),
    ]),
    Component(name: "ast-node", family: "ast", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative", note: ""),
    ]),
    Component(name: "ast-row", family: "ast", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; gap: 0.5rem; padding: 0.13rem 0.1rem; font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.78rem; line-height: 1.5", note: ""),
    ]),
    Component(name: "ast-kind", family: "ast", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "flex: none; padding: 0.04rem 0.4rem; border-radius: 0.34rem; background: color-mix(in srgb, var(--accent) 16%, transparent); color: var(--accent); font-size: 0.68rem; font-weight: 700; letter-spacing: 0.04em", note: ""),
    ]),
    Component(name: "ast-value", family: "ast", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "color: var(--text)", note: ""),
    ]),
    Component(name: "ast-preview", family: "ast", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "color: var(--muted); overflow: hidden; text-overflow: ellipsis; white-space: nowrap", note: ""),
    ]),
    Component(name: "ast-id", family: "ast", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "margin-left: auto; flex: none; color: color-mix(in srgb, var(--muted) 70%, transparent); font-size: 0.66rem", note: ""),
    ]),
    Component(name: "ast-empty", family: "ast", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding: 1.4rem 0.5rem; color: var(--muted); font-size: 0.82rem; text-align: center", note: ""),
    ]),
    Component(name: "code-attachment", family: "code", doc: "", element: "", rules: @[
      Rule(part: " .code-view", kind: stBase, flag: "", sel: "", decls: "min-height: 0", note: ""),
      Rule(part: " .monaco-shell", kind: stBase, flag: "", sel: "", decls: "min-height: 12rem", note: ""),
      Rule(part: " .monaco-host", kind: stBase, flag: "", sel: "", decls: "height: clamp(12rem, 30vh, 19rem)", note: ""),
      Rule(part: " .code-pane[data-pane=\"ast\"]", kind: stBase, flag: "", sel: "", decls: "max-height: clamp(12rem, 30vh, 19rem)", note: ""),
    ]),
    Component(name: "code-signature", family: "code", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding: 0.5rem 0.7rem; border-bottom: 1px solid var(--hairline)", note: ""),
      Rule(part: " .sig-chip", kind: stBase, flag: "", sel: "", decls: "cursor: default", note: ""),
      Rule(part: "", kind: stFlag, flag: "nav", sel: "", decls: "border-top: 0", note: ""),
    ]),
    Component(name: "sig-row", family: "sig", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; flex-wrap: wrap; align-items: center; gap: 0.34rem; font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace", note: ""),
    ]),
    Component(name: "sig-label", family: "sig", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "color: var(--muted); font-size: 0.62rem; text-transform: uppercase; letter-spacing: 0.12em", note: ""),
    ]),
    Component(name: "sig-arrow", family: "sig", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "color: var(--muted); margin: 0 0.15rem", note: ""),
    ]),
    Component(name: "sig-chip", family: "sig", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding: 0.1rem 0.46rem; border: 1px solid var(--hairline); border-radius: 0.4rem; background: var(--control-bg); color: var(--text); font-family: inherit; font-size: 0.74rem; cursor: pointer", note: ""),
      Rule(part: "", kind: stFlag, flag: "out", sel: "", decls: "border-color: color-mix(in srgb, var(--accent) 45%, var(--hairline)); background: color-mix(in srgb, var(--accent) 12%, transparent)", note: ""),
      Rule(part: "", kind: stFlag, flag: "ghost", sel: "", decls: "color: var(--muted); cursor: default", note: ""),
    ]),
    Component(name: "inspector", family: "inspector", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "margin-bottom: 0.85rem; border: 1px solid color-mix(in srgb, var(--accent) 32%, var(--hairline)); border-radius: 0.9rem; background: color-mix(in srgb, var(--accent) 6%, var(--control-bg)); overflow: hidden", note: ""),
    ]),
    Component(name: "inspector-head", family: "inspector", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: flex-start; justify-content: space-between; gap: 0.75rem; padding: 0.7rem 0.85rem; border-bottom: 1px solid var(--hairline)", note: ""),
    ]),
    Component(name: "inspector-title", family: "inspector", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-width: 0", note: ""),
      Rule(part: " .eyebrow", kind: stBase, flag: "", sel: "", decls: "margin: 0 0 0.16rem; text-transform: uppercase; letter-spacing: 0.14em; font-size: 0.62rem", note: ""),
      Rule(part: " h3", kind: stBase, flag: "", sel: "", decls: "margin: 0; font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 1rem", note: ""),
    ]),
    Component(name: "inspector-sub", family: "inspector", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "margin: 0.16rem 0 0; color: var(--muted); font-size: 0.78rem; font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace", note: ""),
    ]),
    Component(name: "inspector-close", family: "inspector", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "flex: none; width: 1.7rem; height: 1.7rem; border: 1px solid var(--hairline); border-radius: 0.5rem; background: var(--control-bg); color: var(--muted); cursor: pointer", note: ""),
      Rule(part: "", kind: stHover, flag: "", sel: "", decls: "background: var(--control-hover); color: var(--text)", note: ""),
    ]),
    Component(name: "insp-section", family: "insp", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding: 0.55rem 0.85rem; border-bottom: 1px solid var(--hairline)", note: ""),
    ]),
    Component(name: "insp-section-label", family: "insp", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "color: var(--muted); font-size: 0.64rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.13em; margin-bottom: 0.4rem", note: ""),
    ]),
    Component(name: "insp-rows", family: "insp", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: grid; gap: 0.3rem", note: ""),
    ]),
    Component(name: "insp-conn", family: "insp", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; flex-wrap: wrap; align-items: center; gap: 0.36rem", note: ""),
    ]),
    Component(name: "insp-sep", family: "insp", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "color: var(--muted)", note: ""),
    ]),
    Component(name: "insp-meta", family: "insp", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "margin-left: auto; color: var(--muted); font-size: 0.68rem; font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace", note: ""),
    ]),
    Component(name: "insp-line", family: "insp", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.8rem; color: var(--text)", note: ""),
    ]),
    Component(name: "insp-empty", family: "insp", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding: 1rem 0.85rem; color: var(--muted); font-size: 0.82rem", note: ""),
    ]),
    Component(name: "ref-chip", family: "ref", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: inline-flex; align-items: center; padding: 0.06rem 0.42rem; border: 1px solid var(--hairline); border-radius: 0.4rem; background: var(--control-bg); color: var(--text); font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.76rem; line-height: 1.5; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap", note: ""),
      Rule(part: "", kind: stFlag, flag: "pred", sel: "", decls: "color: var(--link); border-color: color-mix(in srgb, var(--link) 32%, var(--hairline)); background: color-mix(in srgb, var(--link) 10%, transparent)", note: ""),
      Rule(part: "", kind: stFlag, flag: "atom", sel: "", decls: "color: var(--warning)", note: ""),
      Rule(part: "", kind: stFlag, flag: "ghost", sel: "", decls: "color: var(--muted); cursor: default", note: ""),
    ]),
    Component(name: "things-layout", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative; display: grid; grid-template-columns: minmax(13rem, 18rem) minmax(0, 1fr); gap: 0; height: 100%; min-height: 0", note: ""),
    ]),
    Component(name: "things-rail", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; flex-direction: column; min-width: 0; min-height: 0; background: var(--control-bg); overflow: hidden", note: ""),
      Rule(part: "", kind: stFlag, flag: "is-dragging", sel: "", decls: "opacity: 0.45", note: ""),
    ]),
    Component(name: "things-rail-head", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; gap: 0.45rem; padding: 0.6rem 0.75rem; border-bottom: 1px solid var(--hairline)", note: ""),
      Rule(part: " .things-rail-count", kind: stBase, flag: "", sel: "", decls: "margin-left: auto", note: ""),
    ]),
    Component(name: "things-rail-title", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "font-size: 0.68rem; font-weight: 700; letter-spacing: 0.18em; color: var(--muted)", note: ""),
    ]),
    Component(name: "things-rail-count", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.72rem; color: var(--muted)", note: ""),
    ]),
    Component(name: "things-filters-bar", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding: 0.5rem 0.6rem; border-bottom: 1px solid var(--hairline)", note: ""),
    ]),
    Component(name: "things-filters-toggle", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "width: 100%; text-align: left; border: 1px solid var(--hairline); border-radius: 0.5rem; background: var(--control-bg); color: var(--muted); padding: 0.34rem 0.5rem; font-size: 0.72rem; letter-spacing: 0.04em; cursor: pointer", note: ""),
      Rule(part: "", kind: stFlag, flag: "open", sel: "", decls: "color: var(--text); border-color: color-mix(in srgb, var(--accent) 40%, var(--hairline))", note: ""),
    ]),
    Component(name: "things-filter-chips", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; flex-wrap: wrap; gap: 0.3rem; margin-top: 0.45rem", note: ""),
    ]),
    Component(name: "things-filter", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "border: 1px solid var(--hairline); border-radius: 0.4rem; background: transparent; color: var(--muted); padding: 0.16rem 0.5rem; font-size: 0.7rem; cursor: pointer", note: ""),
      Rule(part: "", kind: stFlag, flag: "on", sel: "", decls: "border-color: color-mix(in srgb, var(--accent) 50%, var(--hairline)); background: color-mix(in srgb, var(--accent) 12%, transparent); color: var(--text)", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; gap: 0.5rem; border: 1px solid transparent; border-radius: 0.5rem; background: transparent; color: var(--muted); padding: 0.3rem 0.5rem; font-size: 0.8rem; text-align: left; cursor: pointer", note: ""),
      Rule(part: "", kind: stHover, flag: "", sel: "", decls: "background: var(--control-hover)", note: ""),
      Rule(part: "", kind: stFlag, flag: "on", sel: "", decls: "color: var(--text)", note: ""),
    ]),
    Component(name: "things-list", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "flex: 1; min-height: 0; overflow: auto; display: flex; flex-direction: column; gap: 0.18rem; padding: 0.45rem", note: ""),
    ]),
    Component(name: "thing-item", family: "thing", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; gap: 0.5rem; padding: 0.36rem 0.5rem; border: 1px solid transparent; border-radius: 0.55rem; background: transparent; color: var(--text); text-align: left; cursor: pointer; transition: background 0.12s ease, border-color 0.12s ease", note: ""),
      Rule(part: "", kind: stHover, flag: "", sel: "", decls: "background: var(--control-hover)", note: ""),
      Rule(part: "", kind: stFlag, flag: "active", sel: "", decls: "border-color: color-mix(in srgb, var(--accent) 60%, var(--hairline)); background: color-mix(in srgb, var(--accent) 12%, transparent)", note: ""),
    ]),
    Component(name: "thing-label", family: "thing", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.8rem", note: ""),
    ]),
    Component(name: "thing-kind", family: "thing", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "flex: none; padding: 0.04rem 0.4rem; border-radius: 0.32rem; font-size: 0.6rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; background: color-mix(in srgb, var(--muted) 20%, transparent); color: var(--muted)", note: ""),
      Rule(part: "", kind: stFlag, flag: "procedure", sel: "", decls: "background: color-mix(in srgb, var(--accent) 20%, transparent); color: var(--accent)", note: ""),
      Rule(part: "", kind: stFlag, flag: "relation", sel: "", decls: "background: color-mix(in srgb, var(--link) 18%, transparent); color: var(--link)", note: ""),
      Rule(part: "", kind: stFlag, flag: "atom", sel: "", decls: "background: color-mix(in srgb, var(--warning) 20%, transparent); color: var(--warning)", note: ""),
      Rule(part: "", kind: stFlag, flag: "adapter", sel: "", decls: "background: color-mix(in srgb, var(--danger) 18%, transparent); color: var(--danger)", note: ""),
    ]),
    Component(name: "things-main", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; flex-direction: column; min-height: 0; background: var(--assistant); overflow: hidden", note: ""),
    ]),
    Component(name: "things-navbar", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; gap: 0.75rem; padding: 0.5rem 0.7rem; border-bottom: 1px solid var(--hairline); background: color-mix(in srgb, var(--trace) 40%, transparent)", note: ""),
    ]),
    Component(name: "nav-controls", family: "nav", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: inline-flex; gap: 0.3rem", note: ""),
      Rule(part: "", kind: stFlag, flag: "right", sel: "", decls: "margin-left: auto", note: ""),
    ]),
    Component(name: "nav-btn", family: "nav", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "width: 1.85rem; height: 1.85rem; border: 1px solid var(--hairline); border-radius: 0.5rem; background: var(--control-bg); color: var(--text); cursor: pointer; font-size: 0.95rem; line-height: 1", note: ""),
      Rule(part: "", kind: stDisabled, flag: "", sel: "", decls: "opacity: 0.35; cursor: default", note: ""),
    ]),
    Component(name: "nav-breadcrumb", family: "nav", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; gap: 0.4rem; min-width: 0", note: ""),
      Rule(part: "", kind: stFlag, flag: "is-dragging", sel: "", decls: "opacity: 0.5", note: ""),
      Rule(part: " .drag-grip", kind: stBase, flag: "", sel: "", decls: "margin-right: 0.1rem", note: ""),
    ]),
    Component(name: "nav-current", family: "nav", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.86rem; overflow: hidden; text-overflow: ellipsis; white-space: nowrap", note: ""),
      Rule(part: "", kind: stFlag, flag: "muted", sel: "", decls: "color: var(--muted)", note: ""),
    ]),
    Component(name: "things-detail", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "flex: 1; min-height: 0; overflow: auto", note: ""),
    ]),
    Component(name: "things-home", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding: clamp(0.82rem, 3vw, 1.35rem)", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "height: 100%", note: ""),
    ]),
    Component(name: "things-resizer", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "cursor: col-resize; background: var(--hairline); position: relative; transition: background 0.12s ease", note: ""),
      Rule(part: "", kind: stAfter, flag: "", sel: "", decls: "content: \"\"; position: absolute; inset: 0 -4px; z-index: 4", note: ""),
      Rule(part: "", kind: stHover, flag: "", sel: "", decls: "background: color-mix(in srgb, var(--accent) 55%, var(--hairline))", note: ""),
    ]),
    Component(name: "conn-filter-bar", family: "conn", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; flex-wrap: wrap; gap: 0.28rem; margin-bottom: 0.45rem", note: ""),
    ]),
    Component(name: "conn-filter", family: "conn", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "border: 1px solid var(--hairline); border-radius: 999px; background: transparent; color: var(--muted); padding: 0.08rem 0.5rem; font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.68rem; cursor: pointer", note: ""),
      Rule(part: "", kind: stFlag, flag: "active", sel: "", decls: "border-color: color-mix(in srgb, var(--accent) 50%, var(--hairline)); background: color-mix(in srgb, var(--accent) 14%, transparent); color: var(--text)", note: ""),
    ]),
    Component(name: "floating-tip", family: "floating", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: fixed; top: 0; left: 0; z-index: 80; max-width: 22rem; padding: 0.32rem 0.55rem; border: 1px solid var(--hairline); border-radius: 0.5rem; background: var(--panel-solid); color: var(--text); box-shadow: 0 10px 30px rgba(0, 0, 0, 0.35); font-size: 0.74rem; font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; line-height: 1.4; white-space: pre-wrap; pointer-events: none; opacity: 0; transition: opacity 0.1s ease", note: ""),
      Rule(part: "", kind: stFlag, flag: "show", sel: "", decls: "opacity: 1", note: ""),
    ]),
    Component(name: "memory-head-left", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; gap: 0.6rem; min-width: 0", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "gap: 0.7rem", note: ""),
    ]),
    Component(name: "memory-logo", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "width: clamp(5rem, 9vw, 7rem); height: auto; max-height: 1.8rem; object-fit: contain; filter: invert(1)", note: ""),
    ]),
    Component(name: "memory-search-wrap", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative; flex: 1 1 14rem; min-width: 0; display: flex; align-items: center", note: ""),
    ]),
    Component(name: "memory-search-icon", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: absolute; left: 0.4rem; color: var(--muted); pointer-events: none", note: ""),
    ]),
    Component(name: "memory-filter-menu", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative", note: ""),
    ]),
    Component(name: "memory-filter-toggle", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: inline-flex; align-items: center; gap: 0.4rem; min-height: 2.3rem; padding: 0 0.7rem 0 0.85rem; border: 1px solid var(--hairline); border-radius: 0.6rem; background: var(--control-bg); color: var(--text); font-size: 0.82rem; cursor: pointer; white-space: nowrap; transition: background 0.12s ease, border-color 0.12s ease", note: ""),
      Rule(part: "", kind: stAfter, flag: "", sel: "", decls: "content: \"▾\"; font-size: 0.7rem; color: var(--muted); transition: transform 0.15s var(--ease)", note: ""),
      Rule(part: "", kind: stHover, flag: "", sel: "", decls: "background: var(--control-hover)", note: ""),
      Rule(part: "", kind: stFlag, flag: "open", sel: "", decls: "border-color: color-mix(in srgb, var(--accent) 55%, var(--hairline)); background: color-mix(in srgb, var(--accent) 14%, transparent)", note: ""),
      Rule(part: " span", kind: stBase, flag: "", sel: "", decls: "min-width: 1.6rem; padding: 0.05rem 0.34rem; border-radius: 999px; text-align: center; background: color-mix(in srgb, var(--accent) 18%, transparent); color: var(--accent); font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.68rem", note: ""),
    ]),
    Component(name: "memory-filter-pop", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: absolute; top: calc(100% + 0.4rem); right: 0; z-index: 30; display: flex; flex-direction: column; gap: 0.22rem; padding: 0.4rem; border: 1px solid var(--hairline); border-radius: 0.7rem; background: var(--panel-solid); box-shadow: 0 16px 40px rgba(0, 0, 0, 0.4); min-width: 11rem; transform-origin: top right; animation: filterPopIn 0.14s var(--ease)", note: ""),
    ]),
    Component(name: "things-filter-dot", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "width: 0.7rem; height: 0.7rem; border-radius: 0.2rem; border: 1px solid var(--hairline); background: transparent", note: ""),
    ]),
    Component(name: "drag-grip", family: "drag", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "flex: none; width: 0.7rem; height: 0.85rem; border-radius: 2px; background-image: radial-gradient(currentColor 1px, transparent 1.4px); background-size: 0.35rem 0.28rem; color: color-mix(in srgb, var(--muted) 70%, transparent); opacity: 0.7", note: ""),
    ]),
    Component(name: "pane-drag-ghost", family: "pane", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: fixed; top: 0; left: 0; z-index: 90; padding: 0.3rem 0.7rem; border: 1px solid color-mix(in srgb, var(--accent) 50%, var(--hairline)); border-radius: 0.5rem; background: var(--panel-solid); color: var(--text); font-size: 0.68rem; font-weight: 700; letter-spacing: 0.14em; text-transform: uppercase; box-shadow: 0 12px 30px rgba(0, 0, 0, 0.4); pointer-events: none", note: ""),
    ]),
    Component(name: "dock-indicator", family: "dock", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: absolute; z-index: 5; pointer-events: none; border: 2px dashed color-mix(in srgb, var(--accent) 30%, transparent); border-radius: 0.8rem; background: color-mix(in srgb, var(--accent) 4%, transparent); opacity: 0.6; transition: left 0.1s var(--ease), top 0.1s var(--ease), width 0.1s var(--ease), height 0.1s var(--ease), opacity 0.1s ease", note: ""),
      Rule(part: "", kind: stFlag, flag: "dock-active", sel: "", decls: "border-color: color-mix(in srgb, var(--accent) 65%, transparent); background: color-mix(in srgb, var(--accent) 13%, transparent); opacity: 1", note: ""),
    ]),
    Component(name: "memory-active-filters", family: "memory", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; gap: 0.3rem; opacity: 0; max-width: 0; overflow: hidden; transition: opacity 0.18s var(--ease), max-width 0.24s var(--ease)", note: ""),
      Rule(part: "", kind: stFlag, flag: "show", sel: "", decls: "opacity: 1; max-width: 24rem", note: ""),
    ]),
    Component(name: "active-filter-tag", family: "active", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "opacity: 0; transform: translateY(4px); animation: activeTagIn 0.26s var(--ease) forwards; white-space: nowrap", note: ""),
    ]),
    Component(name: "home-side", family: "home", doc: "", element: "", rules: @[
      Rule(part: "", kind: stFlag, flag: "solo", sel: "", decls: "overflow: auto; height: 100%; padding: 0.6rem clamp(0.7rem, 2vw, 1.1rem)", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; flex-direction: column; min-width: 0; overflow: auto", note: ""),
    ]),
    Component(name: "home-split", family: "home", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative; display: grid; grid-template-columns: 1fr; gap: 0.85rem; height: 100%; min-height: 0", note: ""),
    ]),
    Component(name: "home-graph", family: "home", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative; min-height: 18rem; min-width: 0", note: ""),
      Rule(part: " .graph-host", kind: stBase, flag: "", sel: "", decls: "width: 100%; height: 100%; min-height: 0", note: ""),
      Rule(part: " .pane-grip-bar", kind: stBase, flag: "", sel: "", decls: "position: absolute; top: 0.45rem; left: 0.6rem; z-index: 3; margin: 0; padding: 0.1rem 0.2rem; border: 0; border-radius: 0; background: transparent; color: color-mix(in srgb, var(--muted) 80%, transparent); text-shadow: 0 1px 2px rgba(0, 0, 0, 0.4)", note: ""),
    ]),
    Component(name: "things-graph-pinned", family: "things", doc: "", element: "", rules: @[
      Rule(part: " .pane-grip-bar", kind: stBase, flag: "", sel: "", decls: "position: absolute; top: 0.45rem; left: 0.6rem; z-index: 3; margin: 0; padding: 0.1rem 0.2rem; border: 0; border-radius: 0; background: transparent; color: color-mix(in srgb, var(--muted) 80%, transparent); text-shadow: 0 1px 2px rgba(0, 0, 0, 0.4)", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative; display: flex; flex-direction: column; min-height: 0; min-width: 0", note: ""),
      Rule(part: " .graph-host", kind: stBase, flag: "", sel: "", decls: "flex: 1; min-height: 0; border: 0; border-radius: 0", note: ""),
    ]),
    Component(name: "pane-grip-bar", family: "pane", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; gap: 0.4rem; padding: 0.3rem 0.5rem; margin-bottom: 0.45rem; border: 1px solid var(--hairline); border-radius: 0.55rem; background: var(--control-bg); color: var(--muted); font-size: 0.66rem; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase; cursor: grab; flex: none", note: ""),
      Rule(part: "", kind: stFlag, flag: "is-dragging", sel: "", decls: "opacity: 0.5", note: ""),
    ]),
    Component(name: "graph-host", family: "graph", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative; width: 100%; height: 100%; min-height: 18rem; border: 1px solid var(--hairline); border-radius: 1rem; overflow: hidden; background: radial-gradient(circle at 50% 30%, color-mix(in srgb, var(--accent) 9%, transparent), transparent 60%),\n    var(--trace); touch-action: none", note: ""),
      Rule(part: " .memory-oracle", kind: stBase, flag: "", sel: "", decls: "display: block; width: 100%; height: 100%; cursor: grab", note: ""),
    ]),
    Component(name: "graph-legend", family: "graph", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: absolute; top: 0.55rem; right: 0.65rem; display: flex; flex-wrap: wrap; gap: 0.7rem; padding: 0.3rem 0.55rem; border-radius: 0.6rem; background: color-mix(in srgb, var(--panel-solid) 70%, transparent); font-size: 0.66rem; color: var(--muted); pointer-events: none", note: ""),
      Rule(part: " span", kind: stBase, flag: "", sel: "", decls: "display: inline-flex; align-items: center; gap: 0.3rem", note: ""),
      Rule(part: " .dot", kind: stBase, flag: "", sel: "", decls: "width: 0.55rem; height: 0.55rem; border-radius: 50%", note: ""),
      Rule(part: " .dot.code", kind: stBase, flag: "", sel: "", decls: "background: var(--accent)", note: ""),
      Rule(part: " .dot.relation", kind: stBase, flag: "", sel: "", decls: "background: var(--link)", note: ""),
      Rule(part: " .dot.unit", kind: stBase, flag: "", sel: "", decls: "background: var(--text)", note: ""),
      Rule(part: " .dot.value", kind: stBase, flag: "", sel: "", decls: "background: var(--warning)", note: ""),
    ]),
    Component(name: "tile-root", family: "tile", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative; height: 100%; min-height: 0; min-width: 0", note: ""),
    ]),
    Component(name: "pane-split", family: "pane", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative; display: grid; height: 100%; min-height: 0; min-width: 0", note: ""),
      Rule(part: " > [data-tpane]", kind: stBase, flag: "", sel: "", decls: "min-width: 0; min-height: 0", note: ""),
      Rule(part: " > [data-pane-key]", kind: stBase, flag: "", sel: "", decls: "min-width: 0; min-height: 0", note: ""),
    ]),
    Component(name: "pane-resizer", family: "pane", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative; background: var(--hairline); transition: background 0.12s ease", note: ""),
      Rule(part: "", kind: stAfter, flag: "", sel: "", decls: "content: \"\"; position: absolute; z-index: 4", note: ""),
      Rule(part: "", kind: stHover, flag: "", sel: "", decls: "background: color-mix(in srgb, var(--accent) 55%, var(--hairline))", note: ""),
    ]),
    Component(name: "body-toggle", family: "body", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "width: 2.1rem; height: 1.2rem; border-radius: 999px; border: 1px solid var(--hairline); background: var(--control-bg); position: relative; cursor: pointer; padding: 0; transition: background 0.14s var(--ease), border-color 0.14s var(--ease)", note: ""),
      Rule(part: " .body-toggle-knob", kind: stBase, flag: "", sel: "", decls: "position: absolute; top: 1px; left: 1px; width: calc(1.2rem - 4px); height: calc(1.2rem - 4px); border-radius: 50%; background: var(--muted); transition: transform 0.14s var(--ease), background 0.14s var(--ease)", note: ""),
      Rule(part: "", kind: stFlag, flag: "on", sel: "", decls: "background: color-mix(in srgb, var(--accent) 24%, transparent); border-color: color-mix(in srgb, var(--accent) 55%, var(--hairline))", note: ""),
    ]),
    Component(name: "graph-hint", family: "graph", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: absolute; bottom: 0.5rem; left: 0.65rem; right: 0.65rem; text-align: center; font-size: 0.64rem; color: var(--muted); opacity: 0.6; pointer-events: none", note: ""),
    ]),
    Component(name: "things-expanded", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; flex-direction: column; height: 100%; min-height: 0", note: ""),
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative", note: ""),
      Rule(part: " .graph-host", kind: stBase, flag: "", sel: "", decls: "flex: 1; border: 0; border-radius: 0", note: ""),
    ]),
    Component(name: "graph-float-controls", family: "graph", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: absolute; top: 0.6rem; right: 0.6rem; z-index: 3; display: flex; gap: 0.35rem", note: ""),
      Rule(part: " .nav-btn", kind: stBase, flag: "", sel: "", decls: "background: color-mix(in srgb, var(--panel-solid) 78%, transparent); backdrop-filter: blur(10px)", note: ""),
    ]),
    Component(name: "things-split", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: relative; display: grid; height: 100%; min-height: 0", note: ""),
    ]),
    Component(name: "graph-bar", family: "graph", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: absolute; top: 0; left: 0; right: 0; z-index: 3; display: flex; align-items: center; gap: 0.5rem; padding: 0.4rem 0.5rem; pointer-events: none; background: linear-gradient(180deg, color-mix(in srgb, var(--trace) 70%, transparent), transparent)", note: ""),
      Rule(part: " > *", kind: stBase, flag: "", sel: "", decls: "pointer-events: auto", note: ""),
    ]),
    Component(name: "graph-bar-title", family: "graph", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "flex: none; cursor: grab; font-size: 0.64rem; font-weight: 700; letter-spacing: 0.14em; text-transform: uppercase; color: var(--muted); padding: 0.1rem 0.2rem", note: ""),
    ]),
    Component(name: "graph-legend-inline", family: "graph", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "margin-left: auto; margin-right: 1rem; display: flex; flex-wrap: wrap; gap: 0.7rem; font-size: 0.64rem; color: var(--muted)", note: ""),
      Rule(part: " span", kind: stBase, flag: "", sel: "", decls: "display: inline-flex; align-items: center; gap: 0.3rem", note: ""),
      Rule(part: " .dot", kind: stBase, flag: "", sel: "", decls: "width: 0.55rem; height: 0.55rem; border-radius: 50%", note: ""),
      Rule(part: " .dot.code", kind: stBase, flag: "", sel: "", decls: "background: var(--accent)", note: ""),
      Rule(part: " .dot.relation", kind: stBase, flag: "", sel: "", decls: "background: var(--link)", note: ""),
      Rule(part: " .dot.unit", kind: stBase, flag: "", sel: "", decls: "background: var(--text)", note: ""),
      Rule(part: " .dot.value", kind: stBase, flag: "", sel: "", decls: "background: var(--warning)", note: ""),
    ]),
    Component(name: "graph-unpin", family: "graph", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "flex: none", note: ""),
    ]),
    Component(name: "graph-filters-corner", family: "graph", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "position: absolute; bottom: 0.55rem; left: 0.6rem; z-index: 3; padding: 0.18rem; border-radius: 0.6rem; background: color-mix(in srgb, var(--panel-solid) 55%, transparent); backdrop-filter: blur(8px)", note: ""),
      Rule(part: " .oracle-controls", kind: stBase, flag: "", sel: "", decls: "margin: 0", note: ""),
    ]),
    Component(name: "things-vresizer", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "cursor: row-resize; background: var(--hairline); position: relative; transition: background 0.12s ease", note: ""),
      Rule(part: "", kind: stAfter, flag: "", sel: "", decls: "content: \"\"; position: absolute; inset: -4px 0; z-index: 4", note: ""),
      Rule(part: "", kind: stHover, flag: "", sel: "", decls: "background: color-mix(in srgb, var(--accent) 55%, var(--hairline))", note: ""),
    ]),
    Component(name: "things-browser", family: "things", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "min-height: 0; overflow: hidden", note: ""),
      Rule(part: " .things-layout", kind: stBase, flag: "", sel: "", decls: "height: 100%", note: ""),
    ]),
    Component(name: "detail-band", family: "detail", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding: 0.62rem 0.85rem; border-bottom: 1px solid var(--hairline); color: var(--muted); font-family: \"SFMono-Regular\", ui-monospace, Menlo, Consolas, monospace; font-size: 0.8rem", note: ""),
      Rule(part: " code", kind: stBase, flag: "", sel: "", decls: "color: var(--text)", note: ""),
    ]),
    Component(name: "detail-code", family: "detail", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "border-bottom: 1px solid var(--hairline)", note: ""),
      Rule(part: " .code-pane[data-pane=\"ast\"]", kind: stBase, flag: "", sel: "", decls: "padding: 0.7rem 0.85rem 0.9rem; max-height: clamp(14rem, 38vh, 26rem); overflow: auto; background: var(--trace)", note: ""),
    ]),
    Component(name: "detail-code-head", family: "detail", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "display: flex; align-items: center; justify-content: space-between; gap: 0.7rem; padding: 0.5rem 0.7rem; border-bottom: 1px solid var(--hairline); background: color-mix(in srgb, var(--trace) 30%, transparent)", note: ""),
    ]),
    Component(name: "ast-standalone", family: "ast", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding: 0.7rem 0.85rem 0.9rem", note: ""),
    ]),
    Component(name: "detail-connections", family: "detail", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "padding: 0.2rem 0 0.4rem", note: ""),
      Rule(part: " .insp-section:last-child", kind: stBase, flag: "", sel: "", decls: "border-bottom: 0", note: ""),
    ]),
    Component(name: "monaco-rel-ref", family: "monaco", doc: "", element: "", rules: @[
      Rule(part: "", kind: stBase, flag: "", sel: "", decls: "background: color-mix(in srgb, var(--link) 22%, transparent); border: 1px solid color-mix(in srgb, var(--link) 55%, transparent); border-radius: 0.28rem; box-shadow: inset 0 -1px 0 var(--link); cursor: pointer", note: ""),
      Rule(part: "", kind: stHover, flag: "", sel: "", decls: "background: color-mix(in srgb, var(--link) 36%, transparent)", note: ""),
    ]),
  ]

proc labRaw*(): seq[Rule] =
  ## Selectors the component model does not explain: at-rules, `:root`,
  ## element and multi-element selectors. Carried verbatim so the port is
  ## complete, and counted so the gap is visible rather than hidden.
  result = @[
    Rule(part: "", kind: stRaw, flag: "", sel: ":root", decls: "color-scheme: dark; --bg: #101214; --bg-glow: rgba(75, 117, 255, 0.16); --page-start: #17191d; --page-end: #0c0d0f; --panel: rgba(24, 26, 31, 0.86); --panel-solid: #191b20; --text: #f4f1ea; --muted: #aaa39a; --hairline: rgba(244, 241, 234, 0.12); --user: #0a84ff; --assistant: #202228; --assistant-border: rgba(244, 241, 234, 0.1); --trace: #17191d; --trace-ink: #e8e2d8; --accent: #5bd49c; --warning: #ffc66d; --danger: #ff6b61; --shadow: 0 22px 70px rgba(0, 0, 0, 0.34); --topbar-bg: rgba(16, 18, 20, 0.72); --control-bg: rgba(255, 255, 255, 0.07); --control-hover: rgba(255, 255, 255, 0.12); --control-color: #f2eee7; --mark-bg: #f4f1ea; --mark-color: #101214; --copy: #d6d0c6; --chip-bg: rgba(255, 255, 255, 0.08); --chip-color: #eee8df; --bubble-shadow: 0 1px 0 rgba(255, 255, 255, 0.04); --system-bg: rgba(255, 198, 109, 0.12); --system-border: rgba(255, 198, 109, 0.22); --typing-dot: #aaa39a; --trace-border: rgba(244, 241, 234, 0.1); --trace-panel: rgba(0, 0, 0, 0.18); --trace-toggle-bg: rgba(255, 255, 255, 0.06); --trace-item-border: rgba(244, 241, 234, 0.08); --trace-code: #f0eadf; --composer-bg: rgba(24, 26, 31, 0.86); --tab-bg: rgba(255, 255, 255, 0.06); --tab-active-bg: rgba(255, 255, 255, 0.14); --tab-color: #c9c0b6; --send-bg: #f4f1ea; --send-color: #111214; --placeholder: #8e877d; --link: #7ab7ff; --radius: 24px; --ease: cubic-bezier(0.2, 0.8, 0.2, 1); font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ":root[data-theme=\"light\"]", decls: "color-scheme: light; --bg: #f7f4ef; --bg-glow: rgba(255, 255, 255, 0.8); --page-start: #fbfaf7; --page-end: #eee9df; --panel: rgba(255, 255, 255, 0.86); --panel-solid: #ffffff; --text: #1d1d1f; --muted: #72706b; --hairline: rgba(30, 28, 24, 0.12); --assistant: #ffffff; --assistant-border: rgba(30, 28, 24, 0.1); --trace: #f1eee8; --trace-ink: #35322d; --accent: #178f5c; --warning: #a0641b; --danger: #b42318; --shadow: 0 18px 60px rgba(34, 28, 20, 0.12); --topbar-bg: rgba(247, 244, 239, 0.72); --control-bg: rgba(255, 255, 255, 0.62); --control-hover: #fff; --control-color: #35322d; --mark-bg: #141412; --mark-color: #fff8ec; --copy: #53504a; --chip-bg: #fff; --chip-color: #302d28; --bubble-shadow: 0 1px 0 rgba(0, 0, 0, 0.04); --system-bg: #fff7e8; --system-border: rgba(160, 100, 27, 0.2); --typing-dot: #9b9890; --trace-border: rgba(30, 28, 24, 0.1); --trace-panel: rgba(255, 255, 255, 0.62); --trace-toggle-bg: rgba(241, 238, 232, 0.82); --trace-item-border: rgba(30, 28, 24, 0.08); --trace-code: #27231f; --composer-bg: rgba(255, 255, 255, 0.86); --tab-bg: #f0ede6; --tab-active-bg: #fff; --tab-color: #5d5951; --send-bg: #161513; --send-color: #fff; --placeholder: #8c887f; --link: #0a66d8", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "*", decls: "box-sizing: border-box", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "*", decls: "scrollbar-width: thin; scrollbar-color: color-mix(in srgb, var(--muted) 38%, transparent) transparent", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "*::-webkit-scrollbar", decls: "width: 10px; height: 10px; background: transparent", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "*::-webkit-scrollbar-track", decls: "background: transparent", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "*::-webkit-scrollbar-thumb", decls: "background: color-mix(in srgb, var(--muted) 34%, transparent); border-radius: 999px; border: 3px solid transparent; background-clip: padding-box", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "*::-webkit-scrollbar-thumb:hover", decls: "background: color-mix(in srgb, var(--muted) 60%, transparent); background-clip: padding-box", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "*::-webkit-scrollbar-corner", decls: "background: transparent", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "::selection", decls: "background: color-mix(in srgb, var(--accent) 36%, var(--user) 24%); color: var(--text)", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "html", decls: "user-select: none", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "input", decls: "user-select: text", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "textarea", decls: "user-select: text", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "html", decls: "margin: 0; min-height: 100%; background: radial-gradient(circle at 18% -10%, var(--bg-glow), transparent 32rem),\n    linear-gradient(180deg, var(--page-start) 0%, var(--bg) 56%, var(--page-end) 100%); color: var(--text)", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "body", decls: "margin: 0; min-height: 100%; background: radial-gradient(circle at 18% -10%, var(--bg-glow), transparent 32rem),\n    linear-gradient(180deg, var(--page-start) 0%, var(--bg) 56%, var(--page-end) 100%); color: var(--text)", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "body", decls: "min-height: 100vh; overflow: hidden", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "button", decls: "font: inherit", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "textarea", decls: "font: inherit", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "button", decls: "-webkit-tap-highlight-color: transparent", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ":root[data-theme=\"light\"] .brand-logo", decls: "filter: none", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".owl-home:hover .owl-mark", decls: "opacity: 0.24", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".owl-mark.blink .owl-eye", decls: "transform: scaleY(0.08); transition: transform 120ms var(--ease)", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "@media @media (prefers-reduced-motion: reduce)", decls: "", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".trace.collapsed .trace-body", decls: "display: none", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "textarea", decls: "display: block; width: 100%; max-height: 11rem; min-height: 2.34rem; resize: none; border: 0; outline: 0; background: transparent; color: var(--text); line-height: 1.45; padding: 0.42rem 0.15rem", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "textarea::placeholder", decls: "color: var(--placeholder)", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".code-pane[data-pane=\"ast\"]", decls: "padding: 0.7rem 0.85rem 0.9rem; max-height: clamp(17rem, 46vh, 31rem); overflow: auto; background: var(--trace)", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "ul.ast-tree", decls: "list-style: none; margin: 0; padding: 0", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".insp-section:last-child", decls: "border-bottom: 0", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "button.ref-chip:hover", decls: "border-color: color-mix(in srgb, var(--accent) 55%, var(--hairline)); background: color-mix(in srgb, var(--accent) 12%, transparent)", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".memory-item.focusable:hover", decls: "border-color: color-mix(in srgb, var(--accent) 40%, var(--hairline)); background: color-mix(in srgb, var(--accent) 6%, transparent)", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".memory-item.assertion h4", decls: "display: flex; flex-wrap: wrap; align-items: center; gap: 0.34rem", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".nav-btn:hover:not(:disabled)", decls: "background: var(--control-hover); border-color: color-mix(in srgb, var(--accent) 40%, var(--hairline))", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "body.col-resizing", decls: "cursor: col-resize; user-select: none", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ":root[data-theme=\"light\"] .memory-logo", decls: "filter: none", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "#memoryHeading", decls: "min-width: 0; font-family: Inter, ui-sans-serif, system-ui, sans-serif; font-weight: 650; letter-spacing: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".memory-filter-toggle.open::after", decls: "transform: rotate(180deg)", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".memory-filter-pop[hidden]", decls: "display: none", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "@keyframes @keyframes filterPopIn", decls: "", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".things-filter.on .things-filter-dot", decls: "background: var(--accent); border-color: var(--accent)", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".things-rail-head[data-drag-pane]", decls: "cursor: grab", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "body.pane-dragging", decls: "cursor: grabbing; user-select: none", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "@keyframes @keyframes activeTagIn", decls: "", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".home-side.solo .memory-section", decls: "margin-top: 0", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".things-layout.rail-right .things-main", decls: "grid-column: 1", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".things-layout.rail-right .things-resizer", decls: "grid-column: 2", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".things-layout.rail-right .things-rail", decls: "grid-column: 3", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "@media @media (min-width: 60rem)", decls: "", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".nav-breadcrumb[data-drag-pane]", decls: "cursor: grab; border-radius: 0.5rem; padding: 0.1rem 0.3rem", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".nav-breadcrumb[data-drag-pane]:hover", decls: "background: var(--control-hover)", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".pane-split.row > .pane-resizer", decls: "cursor: col-resize", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".pane-split.col > .pane-resizer", decls: "cursor: row-resize", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".pane-split.row > .pane-resizer::after", decls: "inset: 0 -4px", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".pane-split.col > .pane-resizer::after", decls: "inset: -4px 0", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: ".body-toggle.on .body-toggle-knob", decls: "transform: translateX(0.9rem); background: var(--accent)", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "button.ast-row", decls: "width: 100%; border: 0; background: transparent; text-align: left; cursor: pointer; border-radius: 0.32rem", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "button.ast-row:hover", decls: "background: color-mix(in srgb, var(--accent) 10%, transparent)", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "@keyframes @keyframes bubbleIn", decls: "", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "@keyframes @keyframes riseIn", decls: "", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "@keyframes @keyframes pulse", decls: "", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "@keyframes @keyframes sheetIn", decls: "", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "@media @media (max-width: 720px)", decls: "", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "@media @media (max-width: 430px)", decls: "", note: ""),
    Rule(part: "", kind: stRaw, flag: "", sel: "@media @media (prefers-reduced-motion: reduce)", decls: "", note: ""),
  ]
